name: ExecuteQuery_build_main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.Snowflake.ExecuteQuery/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      workdir: Frends.Snowflake.ExecuteQuery
      prebuild_command: |
        echo "Restoring Snowflake private key..."
        echo $env:SNOWFLAKE_PRIVATE_KEY_B64 | base64 -d > rsa_key.p8
        echo "Private key restored at rsa_key.p8"
      env_var_name_1: Snowflake_ConnectionString
      env_var_name_2: Snowflake_PrivateKeyFilePath
      env_var_name_3: Snowflake_PrivateKeyPassphrase
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      env_var_value_1: ${{ secrets.SNOWFLAKE_CONNECTIONSTRING }}
      env_var_value_2: rsa_key.p8
      env_var_value_3: ${{ secrets.SNOWFLAKE_PRIVATEKEYPASSPHRASE }}