name: ExecuteQuery_build_test

on:
  push:
    branches-ignore: 
      - main
    paths:
      - 'Frends.Snowflake.ExecuteQuery/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      workdir: Frends.Snowflake.ExecuteQuery
      env_var_name_1: Snowflake_ConnectionString
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      env_var_value_1: ${{ secrets.SNOWFLAKE_CONNECTIONSTRING }}